version: '3'
services:
  pythonmain:
    container_name: "pythonmain"
    image: python:3.8.12-bullseye
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 5000:5000
    command: sleep infinity
  database:
    container_name: "pythondatabase"
    build:
      context: ./
      dockerfile: mariadb
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
      MARIADB_ROOT_PASSWORD: "root"
    volumes:
      - ../my.cnf:/etc/mysql/conf.d/my.cnf
      - ../root/:/root/
