version: '3'
services:
  pythonmain:
    container_name: "pythonmain"
    image: python:3.8.12-bullseye
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 5000:5000
    command: sleep infinity
